### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by monigoldj** [tullamods/Ludwig#17]
Several crafting resources seem to be missing: copper ore, copper bar, bruiseweed, peacebloom, iron bar. There are many others.

**Comment by SonGokuSSJ** [comment]
Just wanted to add that I tried the addon yesterday and that Celumbra, the Night's Dichotomy is also missing in the database. It is a legion crafted item. 

https://www.wowhead.com/item=146666/celumbra-the-nights-dichotomy

**Comment by Jaliborc** [comment]
Yes. Blizzard changed how their item information API works so much and made it so hard to make any request that I didn't have the time to look into it yet.

I mean, I did, but I realized it was gonna take a long time, not something I could do in a couple of hours.

**Comment by SonGokuSSJ** [comment]
Thank you for the answer (and sorry for the late reply). I have no problem, if it cannot be done in some hours (or even days), but it would be nice if this won't be forgotten in the long term (some weeks to months).
