### ISSUE TITLE
Update for Shadowlands

### ISSUE THREAD

**Issue by zippoking** [tullamods/Ludwig#21]
Hey Tuller,

absolutely loved this addon in earlier expansions. After taking a break in BFA i am coming back to WoW for Shadowlands. 
Any chance that you will update this addon? It was the best ingame database addon.

Thank you for you work!
Best regards
Zippoking

**Comment by jahirahdk** [comment]
As a fellow returning player I've been scouring the web to find a searchable item database addon and although I've never had the pleasure of trying "Ludwig" before, but it appears to be exactly what I am looking for...
As such, I'd like to join @Zippoking in expressing hope that you'd be interested in updating this great project!

**Comment by Jaliborc** [comment]
Working on it. Have the item data, just need to update the list generation algorithm

**Comment by zippoking** [comment]
Hey, 

I was waiting eagerly for an answer. Thank  you so much! 
Can´t wait to test the addon in Shadowlands.
