### ISSUE TITLE
WTB TBC Support?

### ISSUE THREAD

**Issue by darvoso** [tullamods/Ludwig#23]
Currently LW loads empty with errors in TBC Classic because only options in item file are WOW_PROJECT_MAINLINE or WOW_PROJECT_CLASSIC, and nothing for WOW_PROJECT_BURNING_CRUSADE_CLASSIC.  I'm hoping you have a script to dump the item DB from somewhere into that file that makes this an easy request, but I don't know? -)

**Comment by Jaliborc** [comment]
There is currently no blizzard API for burning crusade servers, so Ludwig doesn't work there.

**Comment by kman3107** [comment]
Is Ludwig supposed to be working on TBC now? My addon loads fine (I say that, but I dunno if some addon I have installed is stopping lua errors), but when I try searching for something or linking something, nothing is happening.

**Comment by Jaliborc** [comment]
No, I just meant blizzard meanwhile added an api for the burning crusade server data.
New version out now, fixed.
