### ISSUE TITLE
Errors in TBCC on /lw Load

### ISSUE THREAD

**Issue by honorgog** [tullamods/Ludwig#24]
Date: 2021-07-06 21:09:34
ID: 1
Error occured in: Global
Count: 6
Message: ..\AddOns\Ludwig\addons\data\api.lua line 24:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [string "=[C]"]: pairs()
   [string "@Ludwig\addons\data\api.lua"]:24: Find()
   [string "@Ludwig\addons\window\frame.lua"]:168: Update()
   [string "@Ludwig\addons\window\frame.lua"]:139:
      Ludwig\addons\window\frame.lua:137
   [string "=[C]"]: Show()
   [string "@..\FrameXML\UIParent.lua"]:2100: SetUIPanel()
   [string "@..\FrameXML\UIParent.lua"]:1945: ShowUIPanel()
   [string "@..\FrameXML\UIParent.lua"]:1806:
      ..\FrameXML\UIParent.lua:1802
   [string "=[C]"]: SetAttribute()
   [string "@..\FrameXML\UIParent.lua"]:2571: ShowUIPanel()
   [string "@Ludwig\addons\window\frame.lua"]:133: Toggle()
   [string "@Ludwig\addons\main\main.lua"]:15: ToggleSearchFrame()
   [string "@Ludwig\addons\main\slash.lua"]:29: ?()
   [string "@..\FrameXML\ChatFrame.lua"]:4825: ChatEdit_ParseText()
   [string "@..\FrameXML\ChatFrame.lua"]:4488: ChatEdit_SendText()
   [string "@..\FrameXML\ChatFrame.lua"]:4524: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

***

Date: 2021-07-06 21:10:30
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Ludwig\addons\data\api.lua line 94:
   attempt to index global 'Ludwig_Items' (a nil value)
Debug:
   [string "@Ludwig\addons\data\api.lua"]:94: ClassExists()
   [string "@Ludwig\addons\window\dropdowns.lua"]:76: initFunction()
   [string "@..\FrameXML\UIDropDownMenu.lua"]:79: UIDropDownMenu_Initialize()
   [string "@..\FrameXML\UIDropDownMenu.lua"]:1110:
      ..\FrameXML\UIDropDownMenu.lua:975
   [string "=[C]"]: ToggleDropDownMenu()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
self = <table> {
 FindClosest = <function> defined @Interface\AddOns\Ludwig\addons\data\api.lua:57
 GetLink = <function> defined @Interface\AddOns\Ludwig\addons\data\api.lua:109
 ClassExists = <function> defined @Interface\AddOns\Ludwig\addons\data\api.lua:88
 Find = <function> defined @Interface\AddOns\Ludwig\addons\data\api.lua:17
 HasEquipSlots = <function> defined @Interface\AddOns\Ludwig\addons\data\api.lua:98
}
class = 0
subclass = nil
slot = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'Ludwig_Items' (a nil value)"

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  WowheadLooter, v20501
  AdvancedInterfaceOptions, v1.6.0
  Armory, vv1.1.1
  Atlas, vv1.49.01
  AtlasClassicWoW, vv1.49.00
  AtlasTransportation, vv1.49.00
  AucAdvanced, v1.13.6707 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucScanData, v1.13.6630 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  BankItems, v2.55
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BuffTimers, vv1.5.0
  ClassicAutoDismount, v1.02
  ClassicCastbars, vv1.4.0
  ClassicCastbarsOptions, vv1.4.0
  Critline, v4.6.14
  CritlineAuraMonitor, v4.6.14
  CTCore, v9.0.5.6
  CTExpenseHistory, v9.0.5.3
  CTLibrary, v9.0.5.5
  CTMailMod, v9.0.5.6
  CTPartyBuffs, v9.0.5.6
  CTUnitFrames, v9.0.5.6
  DBMCore, v2.5.8-2-g21844b5
  DBMStatusBarTimers, v
  Enchantrix, v1.13.6708 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6697 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.8.9
  FishingBuddy, v0.7.5.5
  FlashSay, v1.0.1.20501
  GatherMate2, v1.46.1-classic
  GlobalIgnoreList, v1.13.10
  GuildRosterManager, v1.9291
  HealBotData, v2.5.1.12
  HealBoten, v2.5.1.12
  HealBotOptions, v2.5.1.12
  InFlightLoad, v1.13.005
  Informant, v1.13.6684 (SwimmingSeadragon)
  Ludwig, v9.1.0
  LudwigData, v9.1.0
  LudwigWindow, v9.1.0
  myReputationClassic, v1.0.2.20501
  QuestFrameFixer, v1.2
  QuestIconDesaturation, v3.2
  Questie, v6.4.1
  Recount, vv2.5.1b
  SilverDragon, vv20501.0
  SilverDragonBurningCrusade, vv20501.0
  SilverDragonClassic, vv20501.0
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Stubby, v1.13.6614 (SwimmingSeadragon)
  ThreatClassic2, v2.37
  TitanClassic, v1.3.4.20501
  TitanClassicAmmo, v1.3.4.20501
  TitanClassicBag, v1.3.4.20501
  TitanClassicClock, v1.3.4.20501
  TitanClassicDefense, v5.0.5.20501
  TitanClassicGold, v1.3.4.20501
  TitanClassicItemDed, v1.0.0.4
  TitanClassicLocation, v1.3.4.20501
  TitanClassicLootType, v1.3.4.20501
  TitanClassicPerformance, v1.3.4.20501
  TitanClassicRecount, v1.0.2.20501
  TitanClassicRegen, v1.3.4.20501
  TitanClassicRepair, v1.3.4.20501
  TitanClassicVolume, v1.3.4.20501
  TitanClassicXP, v1.3.4.20501
  TitanCraftCooldown, v1.0.0.00002
  WowLua, vv80000-1.0.0
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=9b3)

**Comment by Jaliborc** [comment]
There is currently no blizzard API for burning crusade servers, so Ludwig doesn't work there.

**Comment by Jaliborc** [comment]
Fixed
