### ISSUE TITLE
Hands filter for every armor type is missing in the Vanilla Classic version

### ISSUE THREAD

**Issue by PaperCuTTzi** [tullamods/Ludwig#25]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Ludwig-9.1.1-1.13.7.zip
 - Server patch: 1.13.7

 **Have you read the changelog? (please don't waste our time)**
Yep.

**Describe the bug**
The filter for hands is missing for every armor type.

**To Reproduce**
Steps to reproduce the behaviour:
1. type in "/ludwig"
2. click on the right bottom dropdown menu displaying "All"
3. go to "Armor"
4. try to find any armor for hands

**Comment by Jaliborc** [comment]
Fixed
